import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import React from 'react';

/**
 * Data Layer Class B on Create Deal (crm.deal, create.section slot), behind
 * submodule:data_layer:custom_fields. Save path: Class B values ride the
 * native POST /deals payload as `custom_fields`, merged with the legacy
 * "Additional Information" values that share the column.
 */

const dl = vi.hoisted(() => ({
  flag: false,
  regs: [] as any[],
  fields: [] as any[],
  layouts: {} as Record<string, any>,
}));
const mockToastError = vi.hoisted(() => vi.fn());

function ProbeSection(props: any) {
  return (
    <div data-testid={`section-${props.registration.id}`} data-entity={props.datasetCode} data-mode={props.mode} data-save-mode={props.saveMode}>
      <button type="button" onClick={() => props.onValuesChange({ ...props.values, plate: 'KL-01' })}>fill-plate</button>
    </div>
  );
}

const mockCreateDeal = vi.fn();

vi.mock('../../services/crmService', () => ({
  crmService: {
    getUsers: () => Promise.resolve([{ id: 'u1', full_name: 'Alice Rep', email: 'a@t.com' }]),
    getSettings: () => Promise.resolve({
      deal_stages: [{ id: 's1', name: 'Lead' }],
      deal_custom_fields: [{ id: 'legacy1', label: 'Legacy', type: 'text' }],
      default_owner_id: 'u1',
    }),
    getSalesReps: () => Promise.resolve([]),
    getLeadById: () => Promise.resolve({ id: 'lead-1', name: 'John' }),
  },
  dealsApi: {
    create: (...a: any[]) => mockCreateDeal(...a),
    generateName: () => Promise.resolve({ name: 'Acme deal', isAutoGenerated: false }),
  },
}));

vi.mock('@so360/design-system', () => ({ toast: { error: mockToastError, success: vi.fn() } }));

vi.mock('@so360/shell-context', () => ({
  useBusinessSettings: () => ({ settings: { base_currency: 'USD', document_language: 'en-US', timezone: 'UTC' } }),
  useActivity: () => ({ recordActivity: () => Promise.resolve() }),
  useOrganization: () => ({ currentOrg: { id: 'org-1' } }),
  useQuota: () => ({ quotas: [], isLoading: false, error: null, isExceeded: () => false, getQuota: () => null, getPercentage: () => 0, refresh: async () => {} }),
  useShellBridge: () => ({
    effectiveFlagsLoaded: true, isAdmin: false,
    isFeatureEnabled: (k: string) => (k === 'submodule:data_layer:custom_fields' ? dl.flag : true),
  }),
  useDatasetSchema: () => ({ fields: dl.fields }),
  useSlotRenderers: (code: string, slot: string) =>
    dl.regs
      .filter((r: any) => r.dataset_code === code && r.slot === slot)
      .map((r: any) => ({ registration: r, Renderer: ProbeSection, key: r.id })),
  registerRecordLayout: (def: any) => { dl.layouts[def.entity] = def; return () => {}; },
  getRecordLayout: (entity: string) => dl.layouts[entity] ?? null,
}));

import CreateDealModal from './CreateDealModal';

const SECTION = { id: 'cs1', dataset_code: 'crm.deal', slot: 'create.section', renderer: 'custom_fields' };
const props = { leadId: 'lead-1', leadName: 'John Doe', companyName: 'Acme', onClose: vi.fn(), onSuccess: vi.fn() };

beforeEach(() => {
  vi.clearAllMocks();
  dl.flag = false;
  dl.regs = [SECTION];
  dl.fields = [{ field_key: 'plate', label: 'Plate', field_type: 'text', required: false }];
  dl.layouts = {};
  mockCreateDeal.mockResolvedValue({ id: 'd-new', name: 'Acme deal' });
});

describe('Feature: Class B custom fields on Create Deal', () => {
  it('Given the flag is off / When the deal is submitted / Then no section renders and custom_fields is not sent', async () => {
    render(<CreateDealModal {...props} />);
    await waitFor(() => expect(screen.getByText('Legacy')).toBeTruthy());
    expect(screen.queryByTestId('section-cs1')).toBeNull();
    fireEvent.submit(document.querySelector('form')!);
    await waitFor(() => expect(mockCreateDeal).toHaveBeenCalled());
    expect(mockCreateDeal.mock.calls[0][0].custom_fields).toBeUndefined();
  });

  it('Given the flag is on / When the modal opens / Then the create.section renders for crm.deal in create mode with native save', async () => {
    dl.flag = true;
    render(<CreateDealModal {...props} />);
    const section = await screen.findByTestId('section-cs1');
    expect(section.getAttribute('data-entity')).toBe('crm.deal');
    expect(section.getAttribute('data-mode')).toBe('create');
    expect(section.getAttribute('data-save-mode')).toBe('native');
  });

  it('Given Class B and legacy values / When the deal is submitted / Then both are sent in the native create payload custom_fields', async () => {
    dl.flag = true;
    render(<CreateDealModal {...props} />);
    await waitFor(() => expect(screen.getByText('Legacy')).toBeTruthy());
    const legacyInput = screen.getByText('Legacy').parentElement!.querySelector('input')!;
    fireEvent.change(legacyInput, { target: { value: 'L' } });
    fireEvent.click(await screen.findByText('fill-plate'));
    fireEvent.submit(document.querySelector('form')!);
    await waitFor(() => expect(mockCreateDeal).toHaveBeenCalled());
    expect(mockCreateDeal.mock.calls[0][0].custom_fields).toEqual({ legacy1: 'L', plate: 'KL-01' });
  });

  it('Given a required Class B field is empty / When the deal is submitted / Then the create is blocked with a message naming the field', async () => {
    dl.flag = true;
    dl.fields = [{ field_key: 'plate', label: 'Plate', field_type: 'text', required: true }];
    render(<CreateDealModal {...props} />);
    await screen.findByTestId('section-cs1');
    fireEvent.submit(document.querySelector('form')!);
    await waitFor(() => expect(mockToastError).toHaveBeenCalledWith('Please fill in: Plate'));
    expect(mockCreateDeal).not.toHaveBeenCalled();
  });

  it('Given a hidden create.section registration / When the flag is on / Then it is not rendered', async () => {
    dl.flag = true;
    dl.regs = [{ ...SECTION, visibility_profile: 'hidden' }];
    render(<CreateDealModal {...props} />);
    await waitFor(() => expect(screen.getByText('Legacy')).toBeTruthy());
    expect(screen.queryByTestId('section-cs1')).toBeNull();
  });
});
