import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import React from 'react';

const mockPreview = vi.fn();
const mockUpdate = vi.fn();

vi.mock('../../../services/crmService', () => ({
  crmService: {
    previewDealNamingSettings: (...a: any[]) => mockPreview(...a),
    updateDealNamingSettings: (...a: any[]) => mockUpdate(...a),
  },
}));

import DealNamingSettingsTab from './DealNamingSettingsTab';

const BASE_CONFIG = {
  enabled: true,
  template: '{lead_name} - {YYYYMMDD}',
  prefix: '',
  suffix: '',
  separator: ' - ',
  sequence: { enabled: false, reset_mode: 'none' as const, padding: 4, start_at: 1 },
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.useFakeTimers({ shouldAdvanceTime: true });
  mockPreview.mockResolvedValue({ name: 'Acme - 20260804', isAutoGenerated: true });
  mockUpdate.mockResolvedValue(BASE_CONFIG);
});

afterEach(() => {
  vi.useRealTimers();
});

describe('Given DealNamingSettingsTab', () => {
  const defaultProps = {
    initialConfig: BASE_CONFIG,
    canWrite: true,
    showSuccess: vi.fn(),
    showError: vi.fn(),
  };

  it('When rendered / Then shows the naming template field pre-filled', () => {
    render(<DealNamingSettingsTab {...defaultProps} />);
    expect(screen.getByDisplayValue('{lead_name} - {YYYYMMDD}')).toBeInTheDocument();
  });

  it('When a token chip is clicked / Then it is inserted into the template field', () => {
    render(<DealNamingSettingsTab {...defaultProps} />);
    fireEvent.click(screen.getByTitle('0001'));
    expect(screen.getByDisplayValue('{lead_name} - {YYYYMMDD}{seq}')).toBeInTheDocument();
  });

  it('When the template changes / Then the debounced preview call fires with the draft config', async () => {
    render(<DealNamingSettingsTab {...defaultProps} />);
    const input = screen.getByDisplayValue('{lead_name} - {YYYYMMDD}');
    fireEvent.change(input, { target: { value: 'DL-{seq}' } });

    await vi.advanceTimersByTimeAsync(500);

    await waitFor(() => {
      expect(mockPreview).toHaveBeenCalledWith(
        expect.objectContaining({ template: 'DL-{seq}' }),
      );
    });
  });

  it('When Save Configuration is clicked / Then calls updateDealNamingSettings', async () => {
    render(<DealNamingSettingsTab {...defaultProps} />);
    fireEvent.click(screen.getByText(/save configuration/i));
    await waitFor(() => {
      expect(mockUpdate).toHaveBeenCalled();
    });
  });

  it('When auto-generate is toggled off / Then the rest of the form is disabled and no preview call is made for existing values', () => {
    render(<DealNamingSettingsTab {...defaultProps} />);
    fireEvent.click(screen.getByText(/auto-generate deal names/i));
    expect(screen.getByText(/manual entry only/i)).toBeInTheDocument();
  });

  it('When canWrite is false / Then the Save Configuration button is not rendered', () => {
    render(<DealNamingSettingsTab {...defaultProps} canWrite={false} />);
    expect(screen.queryByText(/save configuration/i)).not.toBeInTheDocument();
  });
});
