import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import React from 'react';

const mockPreview = vi.fn();

vi.mock('../../../services/crmService', () => ({
  crmService: {
    previewDealNamingSettings: (...a: any[]) => mockPreview(...a),
  },
}));

import DealNamingSettingsTab from './DealNamingSettingsTab';

const BASE_CONFIG = {
  enabled: true,
  template: '{lead_name} - {YYYYMMDD}',
  prefix: '',
  suffix: '',
  separator: ' - ',
  sequence: { enabled: false, reset_mode: 'none' as const, padding: 4, start_at: 1 },
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.useFakeTimers({ shouldAdvanceTime: true });
  mockPreview.mockResolvedValue({ name: 'Acme - 20260804', isAutoGenerated: true });
});

afterEach(() => {
  vi.useRealTimers();
});

describe('Given DealNamingSettingsTab', () => {
  const defaultProps = () => ({
    initialConfig: BASE_CONFIG,
    canWrite: true,
    onChange: vi.fn(),
  });

  it('When rendered / Then shows the naming template field pre-filled', () => {
    render(<DealNamingSettingsTab {...defaultProps()} />);
    expect(screen.getByDisplayValue('{lead_name} - {YYYYMMDD}')).toBeInTheDocument();
  });

  it('When a token chip is clicked / Then it is inserted into the template field', () => {
    render(<DealNamingSettingsTab {...defaultProps()} />);
    fireEvent.click(screen.getByTitle('0001'));
    expect(screen.getByDisplayValue('{lead_name} - {YYYYMMDD}{seq}')).toBeInTheDocument();
  });

  it('When the template changes / Then the debounced preview call fires with the draft config', async () => {
    render(<DealNamingSettingsTab {...defaultProps()} />);
    const input = screen.getByDisplayValue('{lead_name} - {YYYYMMDD}');
    fireEvent.change(input, { target: { value: 'DL-{seq}' } });

    await vi.advanceTimersByTimeAsync(500);

    await waitFor(() => {
      expect(mockPreview).toHaveBeenCalledWith(
        expect.objectContaining({ template: 'DL-{seq}' }),
      );
    });
  });

  // Regression coverage for task c23baf51: this tab no longer saves itself —
  // it lifts every edit to the parent via onChange, and the page-level "Save
  // Configuration" button (in SettingsPage.tsx) is the only thing that persists it.
  it('When mounted / Then onChange is called once with the initial config', () => {
    const onChange = vi.fn();
    render(<DealNamingSettingsTab {...defaultProps()} onChange={onChange} />);
    expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ template: '{lead_name} - {YYYYMMDD}' }));
  });

  it('When the template field changes / Then onChange is called with the updated config', () => {
    const onChange = vi.fn();
    render(<DealNamingSettingsTab {...defaultProps()} onChange={onChange} />);
    onChange.mockClear();
    fireEvent.change(screen.getByDisplayValue('{lead_name} - {YYYYMMDD}'), { target: { value: 'DL-{seq}' } });
    expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ template: 'DL-{seq}' }));
  });

  it('When the prefix, suffix, or sequence padding changes / Then onChange reflects each field', () => {
    const onChange = vi.fn();
    render(<DealNamingSettingsTab {...defaultProps()} onChange={onChange} />);
    onChange.mockClear();
    fireEvent.change(screen.getByPlaceholderText('DEAL'), { target: { value: 'DL' } });
    expect(onChange).toHaveBeenLastCalledWith(expect.objectContaining({ prefix: 'DL' }));
  });

  it('When there is no local Save Configuration button / Then a note points to the page-level save action', () => {
    render(<DealNamingSettingsTab {...defaultProps()} />);
    expect(screen.queryByRole('button', { name: /save configuration/i })).not.toBeInTheDocument();
    expect(screen.getByText(/saved with the "save configuration" button at the top of the page/i)).toBeInTheDocument();
  });

  it('When canWrite is false / Then the top-level-save note is hidden too', () => {
    render(<DealNamingSettingsTab {...defaultProps()} canWrite={false} />);
    expect(screen.queryByText(/saved with the "save configuration" button/i)).not.toBeInTheDocument();
  });

  it('When auto-generate is toggled off / Then the rest of the form is disabled and no preview call is made for existing values', () => {
    render(<DealNamingSettingsTab {...defaultProps()} />);
    fireEvent.click(screen.getByText(/auto-generate deal names/i));
    expect(screen.getByText(/manual entry only/i)).toBeInTheDocument();
  });
});
