name: Deploy Crm Frontend to Production

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: Neonbee-ai/neonbee-devops/.github/workflows/neonbee-deploy-prod-vite-mfe.yml@main
    with:
      service_name: crm-fe
      nginx_root: /var/www/cdn.neonbee.app/html/crm
      needs_shell_packages: true
      is_shell: false
      cf_purge_urls: 'https://cdn.neonbee.app/crm/assets/remoteEntry.js,https://cdn.neonbee.app/crm/index.html'
      vite_env: |
        VITE_BASE_URL=https://cdn.neonbee.app/crm/
        VITE_SO360_CORE_API=https://api.neonbee.app/core
        VITE_SO360_CRM_API=https://api.neonbee.app/crm
        VITE_ENVIRONMENT=cloud
    secrets: inherit
